name: Loud Ausform de Madcap
favicon: null
layout_spectrum: 0.15626
typography_spectrum: 0.23929315223358572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5210063168779016
  lightness: 0.22834436758421361
  saturation: 0.46540596312843263
  rhythmicContrast: 0.19117159210145473
purpose: []
