name: Loud Ausform de Madcap
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26ddf0'
    - '#0c658a'
    - '#f09a26'
    - '#dddddd'
    - '#681d56'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
