name: Ausform MadCap
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32205
title: Ausform
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02221f'
    - '#e79a3d'
    - '#b44d75'
    - '#3ccc97'
    - '#f6d0b2'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
