name: Loud Ausform de Madcap
favicon: null
layout_spectrum: 0.15626
typography_spectrum: 0.9581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#b5bbbf'
    - '#747474'
    - '#18a497'
    - '#d62214'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.46540596312843263
  rhythmicContrast: 0.19117159210145473
purpose: []
