name: Loud Ausform de Madcap
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Ausform
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02221f'
    - '#e79a3d'
    - '#b44d75'
    - '#3ccc97'
    - '#f6d0b2'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
